stages:
  - build
  - deploy

image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay2

# For internal build & publish
.repo-configuration: &configure-npm-repo
  # Configure internal repo
  - npm config set strict-ssl false
  - npm config set registry $NPM_REGISTRY
  - npm config set ca null
  - npm config set always-auth true
  - npm config set _auth $NPM_TOKEN

build:
  stage: build
  variables:
    NPM_REGISTRY: $NPM_PRIVATE_REGISTRY
    NPM_TOKEN: $NPM_PRIVATE_TOKEN
  before_script:
    - npm -v
    - node -v
    - npm i -g gulp
    - *configure-npm-repo
  script:
    - npm i
    - gulp build-prod
  artifacts:
    expire_in: 1 hour
    paths:
        - build

deploy-internal:
  stage: deploy
  except:
    - /^.*-dev$/
  variables:
    NPM_REGISTRY: $NPM_PRIVATE_REGISTRY_3KLES
    NPM_TOKEN: $NPM_PRIVATE_TOKEN
  before_script:
    - npm i -g gulp
    - *configure-npm-repo
  script:
    - gulp publish

